"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./ui/layout/header";
import Footer from "./ui/layout/footer";
import getUser from "@/app/conn/conn";
import { useEffect, useState } from "react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Add Bungee font
const bungee = Geist({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-bungee",
  display: "swap",
  preload: true,
  adjustFontFallback: false,
  fallback: ["system-ui", "arial"],
});

export default function RootLayout({
  children,
}) {
  const [user, setUser] = useState(null);
  useEffect(() => {
      getUser().then(data => { 
        console.log(data); 
        setUser(data);
      });
    }, []);
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bungee&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen`}
      >
        <Header user={user}/>
        <main className="content-body">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
